var titles = [   "The Lottery",
    "The Love of Her Life",
    "The Man Next Door",
    "The Man Upstairs",
    "The Man Who Saved Christmas",
    "The Man With Three Wives",
    "The March Sisters at Christmas",
    "The Marriage Fool",
    "The Marsh",
    "The Matador",
    "The Matthew Shepard Story",
    "The Memory Keeper's Daughter",
    "The Mermaid Chair",
    "The Merry In-Laws",
    "The Messengers",
    "The Morrison Murders",
    "The Mothman Prophecies",
    "The Murder of Princess Diana",
    "The Nanny Diaries",
    "The Obsession",
    "The Oh in Ohio",
    "The Only Witness",
    "The Operation",
    "The Other Mother: A Moment of Truth Movie",
    "The Other Woman",
    "The Pact",
    "The Painting",
    "The Party Never Stops",
    "The Pastor's Wife",
    "The Patron Saint of Liars",
    "The Pelican Brief",
    "The Pennsylvania Miners' Story",
    "The People Next Door",
    "The Perfect Assistant",
    "The Perfect Bride",
    "The Perfect Child",
    "The Perfect Daughter",
    "The Perfect Family",
    "The Perfect Holiday",
    "The Perfect Husband: The Laci Peterson Story",
    "The Perfect Marriage",
    "The Perfect Nanny",
    "The Perfect Neighbor",
    "The Perfect Roommate",
    "The Perfect Student",
    "The Perfect Teacher",
    "The Perfect Tenant",
    "The Perfect Wife",
    "The Pilot's Wife",
    "The Positively True Adventures of the Alleged Texas Cheerleader-Murdering Mom",
    "The Preacher's Daughter",
    "The Pregnancy Pact",
    "The Pregnancy Project",
    "The Price of a Broken Heart",
    "The Price She Paid",
    "The Prince of Tides",
    "The Princess & the Marine",
    "The Princess Diaries",
    "The Promise",
    "The Proposal",
    "The Prosecutors",
    "The Queen",
    "The Quiet",
    "The Rage: Carrie 2",
    "The Real St. Nick",
    "The Rendering",
    "The Resident",
    "The Return",
    "The Return of Alex Kelly",
    "The Rival",
    "The Road to Christmas",
    "The Ron Clark Story",
    "The Rosa Parks Story",
    "The Scarlet Letter",
    "The Secret",
    "The Secret Life of Bees",
    "The Secret Life of Zoey",
    "The Secret of Hidden Lake",
    "The Secret Passion of Robert Clayton",
    "The Secret She Carried",
    "The Secretary",
    "The Secrets Of Comfort House",
    "The Secrets of Lake Success",
    "The Shawshank Redemption",
    "The Sight",
    "The Silence of the Lambs",
    "The Sister-In-Law",
    "The Sisterhood of the Traveling Pants",
    "The Sisterhood of the Traveling Pants 2",
    "The Sky's on Fire",
    "The Sleepwalker Killing",
    "The Soul Collector",
    "The Spring",
    "The Staircase Murders",
    "The Stepfather",
    "The Stepsister",
    "The Stepson",
    "The Story of Us",
    "The Stranger Beside Me",
    "The Stranger Game",
    "The Stranger I Married",
    "The Stranger Within",
    "The Substitute",
    "The Surrogacy Trap",
    "The Survivors Club",
    "The Suspect",
    "The Sweetest Thing",
    "The Switch",
    "The Temp",
    "The Tenth Circle",
    "The Terror Inside",
    "The Test of Love",
    "The Thomas Crown Affair",
    "The Thorn Birds (Part 1)",
    "The Thorn Birds (Part 2)",
    "The Thorn Birds (Part 3)",
    "The Thorn Birds (Part 4)",
    "The Thorn Birds (Part 5)",
    "The Three Lives of Karen",
    "The Ticket",
    "The Trophy Wife's Secret",
    "The Truth About Cats and Dogs",
    "The Truth About Jane",
    "The Truth About Love",
    "The Truth About Lying",
    "The Two Mr. Kissels",
    "The Ugly Truth",
    "The United States of Leland",
    "The Unquiet",
    "The Unsaid",
    "The Unspoken Truth",
    "The Wandering Soul Murders",
    "The War Between Us",
    "The Watch",
    "The Wedding Dress",
    "The Wedding Planner",
    "The Wednesday Woman",
    "The Whereabouts of Jenny",
    "The Whole Shebang",
    "The Wife He Met Online",
    "The Witness Files",
    "The Wives He Forgot",
    "The Woman Who Sinned",
    "The Women of Brewster Place",
    "The Wrong Girl",
    "The Wrong Woman",
    "The Wronged Man",
    "Their Eyes Were Watching God",
    "Their Second Chance",
    "Thelma & Louise",
    "Then She Found Me",
    "There Was a Little Boy",
    "These Old Broads",
    "They Come Back",
    "They Shoot Divas, Don't They?",
    "Thicker Than Blood",
    "Things We Lost in the Fire",
    "Things You Can Tell Just by Looking at Her",
    "Thirst",
    "Thirteen",
    "This Boy's Life",
    "This Child Is Mine",
    "Thomas Kinkade's The Christmas Cottage",
    "Those Secrets",
    "Those She Left Behind",
    "Three Secrets",
    "Thrill",
    "Thrill of the Kill",
    "Through the Eyes of a Killer",
    "Thy Neighbor's Wife",
    "Ticket Out",
    "Ties That Bind",
    "Ties That Bind 2009",
    "Till the End of the Night",
    "Time and Again: AN LMN ORIGINAL MOVIE",
    "Time to Say Goodbye?",
    "Tin Cup",
    "Tipping Point",
    "To Be Fat Like Me",
    "To Catch a Killer",
    "To Dance With Olivia",
    "To Face Her Past",
    "To Have and to Hold",
    "To Live Again",
    "To Live For",
    "To Love, Honor & Betray",
    "To Love, Honor and Deceive",
    "To Save the Children",
    "To Serve and Protect",
    "Together Again for the First Time",
    "Too Close to Home",
    "Too Rich: The Secret Life of Doris Duke",
    "Too Young to Be a Dad",
    "Too Young to Die?",
    "Too Young to Marry",
    "Torn Apart",
    "Torso: The Evelyn Dick Story",
    "Total Stranger",
    "Touch and Go",
    "Touched",
    "Touched by a Killer",
    "Touched by Evil",
    "Touching Wild Horses",
    "Tracks of a Killer",
    "Trail of Tears",
    "Transamerica",
    "Trapped",
    "Trapped in a Purple Haze",
    "Trapped: Buried Alive",
    "Trial at Fortitude Bay",
    "Trial by Fire",
    "Trial By Fire (aka Smoke Jumper)",
    "Tribute",
    "Tricks of the Trade",
    "Tripfall",
    "Triple Dog",
    "Tripping Wire",
    "Triumph Over Disaster: The Hurricane Andrew Story",
    "Trophy Wife",
    "Troubled Waters",
    "True Confessions of a Hollywood Starlet",
    "True Crime",
    "True Love",
    "True True Lie",
    "Trust",
    "Truth",
    "Tully",
    "Twelve Mile Road",
    "Twist of Faith",
    "Twisted Desire",
    "Two Against Time",
    "Two Came Back",
    "Two Can Play That Game",
    "Two Mothers for Zachary",
    "Two of Hearts",
    "Two Weeks",
    "Two Weeks Notice",
    "Tyler Perry's The Family That Preys",
    "Ultimate Deception",
    "Unanswered Prayers",
    "Uncaged Heart",
    "Under the Mistletoe",
    "Under the Tuscan Sun",
    "Undercover Christmas",
    "Unfaithful",
    "Unforgivable",
    "Unstable",
    "Unstable (2009)",
    "Unthinkable",
    "Untraceable",
    "Unwed Father",
    "Up Close & Personal",
    "Uptown Girls",
    "Urban Cowboy",
    "V. I. Warshawski",
    "Vacancy",
    "Vacancy 2",
    "Vanished",
    "Vanished Without a Trace",
    "Vanished Without a Trace [1999]",
    "Vendetta II: The New Mafia",
    "Venus & Mars",
    "Verdict in Blood",
    "Vernie",
    "Vicky Cristina Barcelona",
    "Victim of Innocence",
    "Victim of Love",
    "Victim of the Haunt",
    "Victim of the Night",
    "Video Voyeur: The Susan Wilson Story",
    "View From The Top",
    "View of Terror",
    "Violation of Trust",
    "Violets Are Blue",
    "Virtual Lies",
    "Visions of Murder",
    "Visitors of the Night",
    "Voice From the Grave",
    "Volcano: Fire on the Mountain",
    "Vows of Deception",
    "Voyage of Terror",
    "Waiting to Exhale",
    "Waitress",
    "Walking the Halls",
    "Wall of Secrets",
    "Wandering Eye",
    "Wasted",
    "Water's Edge",
    "Waterproof",
    "We Have Your Husband",
    "We the Jury",
    "We Were the Mulvaneys",
    "Weather Girl",
    "Web of Deceit",
    "Web of Deception",
    "Web Of Desire",
    "Web of Lies",
    "Wedding Bell Blues",
    "Wedding Daze",
    "Welcome Home, Roxy Carmichael",
    "What a Girl Wants",
    "What Alice Found",
    "What Color is Love?",
    "What Comes Around",
    "What Girls Learn",
    "What if God Were the Sun?",
    "What Kind of Mother Are You?",
    "What Lies Above",
    "What Makes a Family",
    "What Matters Most",
    "What She Knew",
    "What's Love Got To Do With It",
    "When A Man Loves A Woman",
    "When a Stranger Calls Back",
    "When Andrew Came Home",
    "When Billie Beat Bobby",
    "When Danger Follows You Home",
    "When Harry Met Sally",
    "When He Didn't Come Home",
    "When Husbands Cheat",
    "When Innocence Is Lost",
    "When Justice Fails",
    "When Love Kills: The Seduction of John Hearn",
    "When No One Would Listen",
    "When Secrets Kill",
    "When Strangers Appear",
    "When the Cradle Falls",
    "Where the Heart Is",
    "Where's the Money, Noreen?",
    "While Justice Sleeps",
    "While the Children Sleep",
    "While You Were Sleeping",
    "Whisper",
    "Whispers and Lies",
    "White Christmas",
    "White Oleander",
    "Who Is Clark Rockefeller?",
    "Who Killed Allison Parks?",
    "Whose Daughter is She?",
    "Why I Wore Lipstick to My Mastectomy",
    "Wicked",
    "Wicked Minds",
    "Wicker Park",
    "Wide Awake",
    "Widow on the Hill",
    "Widows",
    "Wife, Mother, Murderer: The Marie Hilley Story",
    "Wild Iris",
    "Will You Merry Me?",
    "Willed to Kill",
    "William & Kate",
    "Willing to Kill: The Texas Cheerleader Story",
    "Wind Chill",
    "Winter of Frozen Dreams",
    "Wisegal",
    "Wishcraft",
    "With Harmful Intent",
    "With Hostile Intent",
    "With Murder in Mind",
    "Within",
    "Witness",
    "Woman on the Ledge",
    "Woman on Top",
    "Woman Undone",
    "Woman With a Past",
    "Wonder Boys",
    "Wounded Heart",
    "Write and Wrong",
    "Yesterday's Chil"];

var terminals = {};
var startwords = [];
var wordstats = {};

for (var i = 0; i < titles.length; i++) {
    var words = titles[i].split(' ');
    terminals[words[words.length-1]] = true;
    startwords.push(words[0]);
    for (var j = 0; j < words.length - 1; j++) {
        if (wordstats.hasOwnProperty(words[j])) {
            wordstats[words[j]].push(words[j+1]);
        } else {
            wordstats[words[j]] = [words[j+1]];
        }
    }
}

var choice = function (a) {
    var i = Math.floor(a.length * Math.random());
    return a[i];
};

var make_title = function (min_length) {
    word = choice(startwords);
    var title = [word];
    while (wordstats.hasOwnProperty(word)) {
        var next_words = wordstats[word];
        word = choice(next_words);
        title.push(word);
        if (title.length > min_length && terminals.hasOwnProperty(word)) break;
    }
    if (title.length < min_length) return make_title(min_length);
    return title.join(' ');
};
